ganados=int(input("digite el numero de partidos ganados"))
perdidos=int(input("digite el numero de partidos perdidos"))
empatados=int(input("digite el numero de partidos empatados"))
puntos=((ganados*3)+(empatados*1))
print("el total de puntos es:", puntos)